version: '3'
services:
  core:
    image: mcr.microsoft.com/dotnet/sdk:7.0-jammy
    command: sleep infinity
    volumes:
      - ..:/workspace
    depends_on:
      - sql
  sql:
    image: mcr.microsoft.com/mssql/server:2022-RTM-ubuntu-20.04
    environment:
      - MSSQL_SA_PASSWORD=Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
